### ISSUE TITLE
[NOTES] [But I also wanted to go to...] - Folder name with ellipses will not pull in git for Windows systems - [Varshan Kumar]

### ISSUE THREAD

**Issue by varshankumar** [Keepingshtum/CS146#128]
Windows file paths cannot contain ellipses (...) which generated this error when trying to pull:

![Screenshot 2024-04-27 120454](https://github.com/Keepingshtum/CS146/assets/41884234/34b50e77-e58b-48fd-a902-0f78a2e55e7b)

A proposed fix for this could be to remove the ellipses in the folder name.

**Comment by Keepingshtum** [comment]
Approved. Should be a simple fix.

**Comment by Keepingshtum** [comment]
Fixed it myself, to make sure everyone else is unblocked: 
https://github.com/Keepingshtum/CS146/commit/8a2c5371a44681e736f82c2d5bfa41b5595021d5
