### ISSUE TITLE
[HW][HW8] - Java Solution Optimizations - [Yeng Her]

### ISSUE THREAD

**Issue by YengHer919** [Keepingshtum/CS146#143]
**Describe your problem.**
The code works great, but here are a few ways to reduce lines and work
Count Characters Efficiently: Instead of iterating over the string to count characters, we can use an array of size 128 (ASCII) to directly count characters. This eliminates the need for a HashMap.
Build Palindrome String Efficiently: Instead of building the palindrome string character by character, we can directly compute the length of the palindrome string based on the character counts.
Avoid Unnecessary Operations: We don't need to construct the entire palindrome string. We only need to calculate its length, so constructing the entire string is unnecessary.

**Describe the solution you'd like**
public class LongestPalindrome {
    public static int longestPalindrome(String s) {
        int[] charCounts = new int[128]; // ASCII characters

        for (char c : s.toCharArray()) {
            if (Character.isLetter(c)) {
                charCounts[c]++;
            }
        }

        int length = 0;
        boolean isSingle = false;

        for (int count : charCounts) {
            length += count / 2 * 2; 
            if (count % 2 == 1 && !isSingle) {
                length++; 
                isSingle = true;
            }
        }

        return length;
    }

    public static void main(String[] args) {
        String s1 = "speediskey";
        System.out.println(longestPalindrome(s1)); //Output 5
    }
}

**Comment by Keepingshtum** [comment]
Not sure if you've raised a PR for this, but you should if you have the code solution already!
