### ISSUE TITLE
[ENHANCEMENT] Add study guide/compressed notes category

### ISSUE THREAD

**Issue by R-Rajaie** [Keepingshtum/CS146#48]
As it stands, having the notes section is a great option for people to get the idea of what happened in each lecture. However, I think it would be more beneficial for people to create their own organization of a final study guide in their own personal "folder". This could open up chances for other people to choose which study guide they like and use that as a source of info. Alternatively, it could be one single study guide organized into subcategories (like the aforementioned algorithms, data structures, paradigms, concepts, etc.) 

This essentially is just the same base information as the lectures, just organized in a different way to make it more approachable to study and refer to. 

For example, in my study guide folder, I would have a folder for algorithms (quicksort, merge sort, etc.), a folder detailing data structures (heaps, graphs, etc.). I could create a consistent formatting to make it easier to digest, like for each sorting algorithm's folder I could have the general 'gist', pseudocode, and time complexity in a single text file, followed by implementations in Java and Python in the other files in the folder.

**Comment by Keepingshtum** [comment]
While that's a neat idea, I'd prefer one communal document for a particular lecture. Other people can add on observations/ ideas/ diagrams as and when they come up with them, and you don't have to click through 44 different folders for one lecture to get the whole picture. 

Thanks for the idea though - keep em coming!

**Comment by Keepingshtum** [comment]
With that said, I do like the idea of a mega-document that is divided into subcategories by concept/ topic. Feel free to work on that if that's what you feel is best. I'll consider this for extra credit.

**Comment by R-Rajaie** [comment]
Sounds good, I'll see what I can cook up. Great opportunity to get my markdown up :D

**Comment by JamesAltizersjsu** [comment]
I will add some comments and markdown for labs 7 and 8

**Comment by Keepingshtum** [comment]
The Compressed Notes directory is now called "Summaries".

**Comment by JamesAltizersjsu** [comment]
I will contribute to "summaries" for some of the lectures on the sorting.
